line-length = 120
indent-width = 4

target-version = "py312"
exclude = [
    "libs/**/*",
    "*/migrations/*",
    #    "*/tests/*",
]

[lint]
# See https://docs.astral.sh/ruff/rules/ for rule descriptions
# See https://docs.astral.sh/ruff/linter/ for tips on rule suppression
select = [
    "F",
    "E",
    "D",
    "UP",
    "W",
    "B",
    "TD",
    "I",
    #"ANN",
    #"C901",
]
ignore = [
    "D1", "D2", "D413", "ANN002", "ANN003", "TD003", "UP038", "B904", "D401", "D404"
]

[lint.isort]
no-sections = false

[format]
# Like Black, use double quotes for strings.
quote-style = "single"