# Generated by Django 5.2.4 on 2025-07-17 22:36

import wiwoapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_price_orderitem_confirmed_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=wiwoapp.utils.generate_order_id, max_length=250, unique=True),
        ),
    ]
