# Generated by Django 5.2.4 on 2025-07-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
    ]
